app:
  check-interval-minutes: 5
  scheduler:
    enable: true
    interval: PT10S
    force-check-delay: PT10S
  database-access-type: JDBC # или JPA
  migrations-dir: classpath:migrations

bot:
  api:
    baseurl: ${BOT_API_BASEURL:http://localhost:8080}
  github-token: ${GITHUB_TOKEN:ghp_PUBLICTOKEN1234567890EXAMPLE}
  stackoverflow:
    key: ${STACKOVERFLOW_KEY:PUBLIC_STACKOVERFLOW_KEY}
    access-token: ${STACKOVERFLOW_ACCESS_TOKEN:PUBLIC_STACKOVERFLOW_ACCESS_TOKEN}

server:
  port: 8080
  error:
    include-message: ALWAYS
    include-binding-errors: ALWAYS
    include-stacktrace: ALWAYS
    include-exception: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: ${POSTGRES_PASSWORD:default_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none # Отключаем автоматическое создание схемы Hibernate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: false
  jackson:
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      write-dates-as-timestamps: false
  application:
    name: scrapper
  main:
    allow-bean-definition-overriding: true

management:
  endpoints:
    web:
      base-path: /api/actuator
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  config: classpath:log4j2-plain.xml
  level:
    org.springframework.boot.context.properties: DEBUG

github:
  base:
    url: ${GITHUB_BASE_URL:https://api.github.com}

stackoverflow:
  base:
    url: ${STACKOVERFLOW_BASE_URL:https://api.stackexchange.com/2.2}

springdoc:
  swagger-ui:
    path: /swagger-ui

rate-limiting:
  capacity: 20
  tokens: 20
  refill-duration: 60

retry:
  strategy: constant
  max-attempts: 3
  first-backoff-seconds: 1
  max-backoff-seconds: 5
  jitter-factor: 0.5
  retryable-status-codes:
    - 500
    - 502
    - 503
    - 504
