app:
  telegram-token: ${APP_TELEGRAM_TOKEN}
scrapper:
  api:
    base-url: ${SCRAPPER_API_BASE_URL:http://scrapper:8081/api}
spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/scrapper
    username: exsellent
    password: ${POSTGRES_PASSWORD:default_password}
    driver-class-name: org.postgresql.Driver
  config:
    import: optional:file:.env
  application:
    name: bot
  jackson:
    time-zone: UTC
server:
  port: 8080
#logging:
#  config: classpath:log4j2-plain.xml
  level:
    org.springframework.core.env: TRACE
    backend.academy.bot: DEBUG
springdoc:
  swagger-ui:
    path: /swagger-ui
http:
  client:
    connectTimeout: 5000
    readTimeout: 10000
retry:
  max-attempts: 3
  first-backoff-seconds: 1
  retryable-status-codes: [500, 502, 503, 504, 429]
rate-limiting:
  request-limit: 100
  window-seconds: 60
