app:
  telegramToken: ${APP_TELEGRAM_TOKEN} #"${TELEGRAM_TOKEN}"

scrapper:
  api:
    base-url: http://localhost:8080/api

spring:
  config:
    import:
      - optional:file:.env[.properties]
  application:
    name: bot

  jackson:
    time-zone: UTC

server:
  port: 8081

logging:
  config: classpath:log4j2-plain.xml
  level:
    org.springframework.core.env: TRACE
    backend.academy.bot: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui

rate-limiting:
  capacity: 20
  tokens: 20
  refill-duration: 60

backoff:
  settings:
    maxAttempts: 1000
    initialDelay: 1000
    multiplier: 2.0
    increment: 1000
    strategy: exponential
  retryableStatusCodes: [500, 502, 503, 504]




conversation:
  timeout:
    minutes: 15

spring.autoconfigure.exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
